FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
COPY turbo.json ./
COPY apps/web/package*.json ./apps/web/

RUN npm ci

COPY apps/web ./apps/web

EXPOSE 3000

CMD ["npm", "run", "dev", "--workspace=@voidnull/web"]
