FROM node:22-alpine
WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY turbo.json ./
COPY packages/database/package*.json ./packages/database/
COPY apps/api/package*.json ./apps/api/

RUN npm install && npm install --prefix apps/api

COPY packages/database ./packages/database
COPY apps/api ./apps/api

RUN cd packages/database && npx prisma generate

EXPOSE 3001

CMD ["npm", "run", "--prefix", "apps/api", "dev"]
